name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk zip unzip zlib1g-dev libncurses5-dev
          sudo apt install -y aidl || sudo apt install -y aidl-1.8
          sudo apt install -y lib32z1 lib32ncurses6

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aida64lite-apk
          path: bin/*.apk
